Models/ErrorViewModel.cs
using System;

namespace Kazka.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/News.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Kazka.Models
{
    public class News : DAL.News
    {
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Kazka.Models;

namespace Kazka.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/NewsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Kazka.DAL;
using Kazka.Models;

namespace Kazka.Controllers
{
    public class NewsController : Controller
    {
        private readonly KazkaDbContext _context;

        public NewsController(KazkaDbContext context)
        {
            _context = context;
        }

        // GET: News
        public async Task<IActionResult> Index()
        {
            return View(await _context.AllNews.ToListAsync());
        }

        // GET: News/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var news = await _context.AllNews
                .FirstOrDefaultAsync(m => m.Id == id);
            if (news == null)
            {
                return NotFound();
            }

            return View(news);
        }
    }
}

Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Views/News/Details.cshtml
@model Kazka.Models.News

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>News</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Body)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Body)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.CreatedAt)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.CreatedAt)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.FileName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.FileName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.IsArchive)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.IsArchive)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/News/Index.cshtml
@model IEnumerable<Kazka.Models.News>

@{
    ViewData["Title"] = "Index";
}

<h2>Index</h2>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Body)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CreatedAt)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FileName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IsArchive)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Body)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CreatedAt)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FileName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IsArchive)
            </td>
            <td>
                <a asp-action="Details" asp-route-id="@item.Id">Details</a>
            </td>
        </tr>
}
    </tbody>
</table>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    
    <title>@ViewData["Title"] - Kazka</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/lib/revolution/revolution-slider.css" />
        <link rel="stylesheet" href="~/css/style.css" />
        <link rel="stylesheet" href="~/lib/jqueryui/jquery-ui.css" />
        <link rel="stylesheet" href="~/css/responsive.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>

    <!-- Responsive -->
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0">
</head>
<body>

    <div class="page-wrapper">
        <partial name="_MainHeader" />

        <!-- Preloader -->
        <div class="preloader"></div>

        @RenderBody()
       
        <partial name="_MainFooter" />
    </div>

    <!--Scroll to top-->
    <div class="scroll-to-top scroll-to-target" data-target=".main-header"><span class="icon fa fa-long-arrow-up"></span></div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/lib/revolution/revolution.min.js"></script>
        <script src="~/lib/fancybox/jquery.fancybox.js"></script>
        <script src="~/lib/OwlCarousel2/owl.carousel.js"></script>
        <script src="~/lib/jqueryui/jquery-ui.js"></script>
        <script src="~/lib/wow/wow.js"></script>
        <script src="~/js/script.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>

    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

Views/Shared/_MainFooter.cshtml
<!--Main Footer-->
<footer class="main-footer" style="background-image:url(images/background/pattern-2.png);">
    <div class="auto-container">
        <!--widgets section-->
        <div class="widgets-section">
            <div class="row clearfix">

                <!--Big Column-->
                <div class="big-column col-md-6 col-sm-12 col-xs-12">
                    <div class="row clearfix">
                        <!--Footer Column-->
                        <div class="footer-column col-md-6 col-sm-6 col-xs-12">
                            <div class="footer-widget logo-widget">
                                <div class="footer-logo">
                                    <a href="index.html"><img src="images/logo-2.png" alt="" /></a>
                                </div>
                                <div class="widget-content">
                                    <div class="text">Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officiaproi-dent, sunt in culpa qui officia dese deserunt...</div>
                                    <ul class="social-links-two">
                                        <li class="facebook"><a href="#"><span class="fa fa-facebook"></span></a></li>
                                        <li class="twitter"><a href="#"><span class="fa fa-twitter"></span></a></li>
                                        <li class="google-plus"><a href="#"><span class="fa fa-google-plus"></span></a></li>
                                        <li class="linkedin"><a href="#"><span class="fa fa-linkedin"></span></a></li>
                                    </ul>
                                </div>
                            </div>
                        </div>

                        <!--Footer Column-->
                        <div class="footer-column col-md-6 col-sm-6 col-xs-12">
                            <!--Links Widget-->
                            <div class="footer-widget links-widget">
                                <div class="footer-title">
                                    <h2>Quick Links</h2>
                                </div>
                                <div class="widget-content">
                                    <ul class="list">
                                        <li><a href="#">Home</a></li>
                                        <li><a href="#">Classes</a></li>
                                        <li><a href="#">Teachers</a></li>
                                        <li><a href="#">Latest News</a></li>
                                        <li><a href="#">Contact Us</a></li>
                                    </ul>
                                </div>
                            </div>
                        </div>

                    </div>
                </div>

                <!--Big Column-->
                <div class="big-column col-md-6 col-sm-12 col-xs-12">
                    <div class="row clearfix">

                        <!--Footer Column-->
                        <div class="footer-column col-md-6 col-sm-6 col-xs-12">
                            <!--Links Widget-->
                            <div class="footer-widget links-widget">
                                <div class="footer-title">
                                    <h2>Categories</h2>
                                </div>
                                <div class="widget-content">
                                    <ul class="list">
                                        <li><a href="#">Painting</a></li>
                                        <li><a href="#">Drawing</a></li>
                                        <li><a href="#">Sports, Games</a></li>
                                        <li><a href="#">Life Science</a></li>
                                        <li><a href="#">Activities & Events </a></li>
                                    </ul>
                                </div>
                            </div>
                        </div>

                        <!--Footer Column-->
                        <div class="footer-column col-md-6 col-sm-6 col-xs-12">

                            <div class="footer-widget subscribe-widget">
                                <div class="footer-title">
                                    <h2>News letter</h2>
                                </div>
                                <div class="widget-content">
                                    <div class="newsletter-form">
                                        <form method="post" action="contact.html">
                                            <div class="form-group">
                                                <input type="text" name="name" value="" placeholder="Name *" required="">
                                            </div>
                                            <div class="form-group">
                                                <input type="email" name="email" value="" placeholder="Email Id" required="">
                                            </div>
                                            <div class="form-group">
                                                <button type="submit" class="theme-btn btn-style-one">SUBSCRIBE</button>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                            </div>

                        </div>

                    </div>
                </div>

            </div>
        </div>

        <!--Footer Bottom-->
        <div class="footer-bottom">
            <div class="row clearfix">
                <div class="column col-md-6 col-sm-6 col-xs-12">
                    <div class="copyright">&copy; Copyrights 2017 Saratov. All Rights Reserved</div>
                </div>
                <div class="column col-md-6 col-sm-6 col-xs-12">
                    <div class="cards"><img src="images/icons/visa-cards.png" alt="" /></div>
                </div>
            </div>
        </div>

    </div>
</footer>

Views/Shared/_MainHeader.cshtml
    <!-- Main Header-->
<header class="main-header">

    <!-- Header Top -->
    <div class="header-top">
        <div class="auto-container clearfix">
            <!--Top Left-->
            <div class="top-left pull-left">
                <ul class="links-nav clearfix">
                    <li><span class="icon fa fa-envelope-o"></span><a href="#">Info@Kindergarten.com</a></li>
                    <li><span class="icon fa fa-phone"></span><a href="#">Call Us Now : 1800 123 4567</a></li>
                </ul>
            </div>

            <!--Top Right-->
            <div class="top-right pull-right">
                <ul class="links-nav clearfix">
                    <li class="language dropdown">
                        <a class="btn btn-default dropdown-toggle" id="dropdownMenu2" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true" href="#">English &ensp;<span class="icon fa fa-caret-down"></span></a>
                        <ul class="dropdown-menu style-one" aria-labelledby="dropdownMenu2">
                            <li><a href="#">English</a></li>
                            <li><a href="#">Русский</a></li>
                            <li><a href="#">Українською</a></li>
                        </ul>
                    </li>
                    <li><a href="#">Login</a></li>
                    <li><a href="#">Sign Up</a></li>
                </ul>
            </div>
        </div>
    </div>
    <!-- Header Top End -->
    <!--Header-Upper-->
    <div class="header-upper">
        <div class="auto-container">

            <div class="logo-outer">
                <div class="logo"><a href="index.html"><img src="images/logo.png" alt="" title=""></a></div>
            </div>

            <div class="nav-outer clearfix">

                <!-- Main Menu -->
                <nav class="main-menu">
                    <div class="navbar-header">
                        <!-- Toggle Button -->
                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                    </div>

                    <div class="navbar-collapse collapse clearfix">
                        <!--Left Nav-->
                        <ul class="navigation left-nav clearfix">
                            <li class="current">
                                <a asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                            </li>
                            <li><a asp-area="" asp-controller="News" asp-action="Index">News</a></li>
                            <li class="dropdown">
                                <a href="#">Classes</a>
                                <ul>
                                    <li><a href="classes.html">Classes</a></li>
                                    <li><a href="classes-single.html">Alphabet matching</a></li>
                                    <li><a href="classes-single.html">Letter matching</a></li>
                                    <li><a href="classes-single.html">Color matching</a></li>
                                    <li><a href="classes-single.html">Little Stars</a></li>
                                    <li><a href="classes-single.html">Smart Turtles</a></li>
                                </ul>
                            </li>
                            <li class="dropdown">
                                <a href="#">Pages</a>
                                <ul>
                                    <li><a href="teachers.html">Teachers</a></li>
                                    <li><a href="features.html">Features</a></li>
                                    <li><a href="error-page.html">404 Page</a></li>
                                </ul>
                            </li>
                        </ul>
                        <!--Right Nav-->
                        <ul class="navigation right-nav clearfix">
                            <li><a href="gallery.html">Gallery</a></li>
                            <li class="dropdown">
                                <a href="#">Blog</a>
                                <ul>
                                    <li><a href="blog.html">Our Blog</a></li>
                                    <li><a href="blog-single.html">Blog Single</a></li>
                                </ul>
                            </li>
                            <li><a href="contact.html">Contact Us</a></li>
                        </ul>
                    </div>
                </nav>

                <!--Search Box-->
                <div class="search-box-outer">
                    <div class="dropdown">
                        <button class="search-box-btn dropdown-toggle" type="button" id="dropdownMenu3" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><span class="fa fa-search"></span></button>
                        <ul class="dropdown-menu pull-right search-panel" aria-labelledby="dropdownMenu3">
                            <li class="panel-outer">
                                <div class="form-container">
                                    <form method="post" action="blog.html">
                                        <div class="form-group">
                                            <input type="search" name="field-name" value="" placeholder="Search Here" required="">
                                            <button type="submit" class="search-btn"><span class="fa fa-search"></span></button>
                                        </div>
                                    </form>
                                </div>
                            </li>
                        </ul>
                    </div>
                </div>

            </div>
        </div>
    </div>
    <!--End Header Upper-->
    <!--Sticky Header-->
    <div class="sticky-header">
        <div class="auto-container clearfix">
            <!--Logo-->
            <div class="logo pull-left">
                <a href="index.html" class="img-responsive"><img src="images/logo-small.png" alt="" title=""></a>
            </div>

            <!--Right Col-->
            <div class="right-col pull-right">
                <!-- Main Menu -->
                <nav class="main-menu">
                    <div class="navbar-header">
                        <!-- Toggle Button -->
                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                    </div>

                    <div class="navbar-collapse collapse clearfix">
                        <ul class="navigation clearfix">
                            <li class="current dropdown">
                                <a href="#">Home</a>
                                <ul>
                                    <li><a href="index.html">Homepage One</a></li>
                                    <li><a href="index-2.html">Homepage Two</a></li>
                                    <li class="dropdown">
                                        <a href="#">Header Styles</a>
                                        <ul>
                                            <li><a href="index.html">Header Style One</a></li>
                                            <li><a href="index-2.html">Header Style Two</a></li>
                                        </ul>
                                    </li>
                                </ul>
                            </li>
                            <li><a href="about.html">About Us</a></li>
                            <li class="dropdown">
                                <a href="#">Classes</a>
                                <ul>
                                    <li><a href="classes.html">Classes</a></li>
                                    <li><a href="classes-single.html">Alphabet matching</a></li>
                                    <li><a href="classes-single.html">Letter matching</a></li>
                                    <li><a href="classes-single.html">Color matching</a></li>
                                    <li><a href="classes-single.html">Little Stars</a></li>
                                    <li><a href="classes-single.html">Smart Turtles</a></li>
                                </ul>
                            </li>
                            <li class="dropdown">
                                <a href="#">Pages</a>
                                <ul>
                                    <li><a href="teachers.html">Teachers</a></li>
                                    <li><a href="features.html">Features</a></li>
                                    <li><a href="error-page.html">404 Page</a></li>
                                </ul>
                            </li>
                            <li><a href="gallery.html">Gallery</a></li>
                            <li class="dropdown">
                                <a href="#">Blog</a>
                                <ul>
                                    <li><a href="blog.html">Our Blog</a></li>
                                    <li><a href="blog-single.html">Blog Single</a></li>
                                </ul>
                            </li>
                            <li><a href="contact.html">Contact Us</a></li>
                        </ul>
                    </div>
                </nav><!-- Main Menu End-->
            </div>

        </div>
    </div>
    <!--End Sticky Header-->

</header>
<!--End Main Header -->